"""add birth date to profile

Revision ID: 3fb7d032a13c
Revises: 685a8f138528
Create Date: 2026-09-10 11:43:07.623570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb7d032a13c'
down_revision: Union[str, Sequence[str], None] = '685a8f138528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('birth_date', sa.Date(), nullable=True))
    op.drop_column('profiles', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'birth_date')
    # ### end Alembic commands ###
